### ISSUE TITLE
Getting an identical values after range.toArray(string, string)

### ISSUE THREAD

**Issue by erisnuts** [gf3/moment-range#125]
I'm getting an identical values in array after range.toArray(string, string)

Here is a [pen](http://codepen.io/erisnuts/pen/pbxVqx)

**Comment by gf3** [comment]
hey @erisnuts you should use `moment#format` instead of the private `_i` property. here's what this looks like in the upcoming v3 release:

<img width="495" alt="screen shot 2016-12-07 at 9 45 33 pm" src="https://cloud.githubusercontent.com/assets/18397/20995680/9de41ebc-bcc6-11e6-9e4a-74aeeb482656.png">

although it should work with `toArray` in the current release
