### ISSUE TITLE
range.by('day') returns only 30 days between 1st and 31st of October when initialised with new Date()

### ISSUE THREAD

**Issue by kadikraman** [gf3/moment-range#91]
```
var dateRange = moment.range(new Date('2015-10-01'), new Date('2015-10-31'));
var array = [];
dateRange.by('days', function(day) { array.push(day) });
console.log(array.length);
>> 30
```

It works as expected when the moment.range is initialised with date strings instead of date objects, e.g.

```
var dateRange = moment.range('2015-10-01', '2015-10-31');
```

Could be something to do with summer time?

```
>> var start = new Date('2015-10-01')
>> start
>> Thu Oct 01 2015 01:00:00 GMT+0100 (BST)
```

```
>> var end = new Date('2015-10-31')
>> end
>> Sat Oct 31 2015 00:00:00 GMT+0000 (GMT)
```

**Comment by kadikraman** [comment]
Although looking at the rendered output now, 30 days kind of makes sense since it is technically 30 days and 23 hours (due to summer time!) so I guess there is nothing you can do about it.

**Comment by kurtextrem** [comment]
I guess we need a (dirty) workaround?

**Comment by Laucsen** [comment]
Wow! It happens in all Octobers? I am computing business days and fall on this problem too.

**Comment by gf3** [comment]
this is definitely fixed in the upcoming v3 release:

<img width="637" alt="screen shot 2016-12-08 at 3 37 56 pm" src="https://cloud.githubusercontent.com/assets/18397/21026859/79ad0310-bd5c-11e6-92fb-218c818e7bcf.png">

also when you pass in a string to moment-range it creates a moment object directly, when you pass a string formatted like that directly to `Date` it may not be in the timezone you expect

**Comment by gf3** [comment]
just opened a PR for [`3.0.0`](https://github.com/gf3/moment-range/pull/138) which incorporates these changes. feel free to leave feedback or raise any questions you may have. thanks again for your contributions
